local Collectibles = {
    {
        id = "old_clay_vase",
        name = "Old Clay Vase",
        rarity = "COMMON",
        value = 35,
        incomePerHour = 2,
        category = "Vase",
    },
    {
        id = "worn_travel_journal",
        name = "Worn Travel Journal",
        rarity = "COMMON",
        value = 45,
        incomePerHour = 3,
        category = "Book",
    },
    {
        id = "bronze_sparrow_statue",
        name = "Bronze Sparrow Statue",
        rarity = "COMMON",
        value = 60,
        incomePerHour = 4,
        category = "Statue",
    },
    {
        id = "moonlit_ink_codex",
        name = "Moonlit Ink Codex",
        rarity = "RARE",
        value = 180,
        incomePerHour = 14,
        category = "Book",
    },
    {
        id = "verdant_duelist_blade",
        name = "Verdant Duelist Blade",
        rarity = "RARE",
        value = 225,
        incomePerHour = 17,
        category = "Sword",
    },
    {
        id = "tideglass_chalice",
        name = "Tideglass Chalice",
        rarity = "RARE",
        value = 260,
        incomePerHour = 19,
        category = "Chalice",
    },
    {
        id = "whispering_opal_mask",
        name = "Whispering Opal Mask",
        rarity = "EPIC",
        value = 620,
        incomePerHour = 48,
        category = "Mask",
    },
    {
        id = "ember_archive_volume",
        name = "Ember Archive Volume",
        rarity = "EPIC",
        value = 760,
        incomePerHour = 56,
        category = "Book",
    },
    {
        id = "stormheart_crystal",
        name = "Stormheart Crystal",
        rarity = "EPIC",
        value = 900,
        incomePerHour = 68,
        category = "Crystal",
    },
    {
        id = "crownless_king_effigy",
        name = "Crownless King Effigy",
        rarity = "LEGENDARY",
        value = 2_200,
        incomePerHour = 165,
        category = "Statue",
    },
    {
        id = "sunforged_oathblade",
        name = "Sunforged Oathblade",
        rarity = "LEGENDARY",
        value = 2_750,
        incomePerHour = 205,
        category = "Sword",
    },
    {
        id = "astral_signet_ring",
        name = "Astral Signet Ring",
        rarity = "LEGENDARY",
        value = 3_100,
        incomePerHour = 230,
        category = "Ring",
    },
    {
        id = "chronicle_of_the_last_comet",
        name = "Chronicle of the Last Comet",
        rarity = "MYTHICAL",
        value = 7_200,
        incomePerHour = 525,
        category = "Book",
    },
    {
        id = "veilpiercer_mask",
        name = "Veilpiercer Mask",
        rarity = "MYTHICAL",
        value = 8_400,
        incomePerHour = 610,
        category = "Mask",
    },
    {
        id = "firstflame_crystal",
        name = "Firstflame Crystal",
        rarity = "MYTHICAL",
        value = 9_600,
        incomePerHour = 700,
        category = "Crystal",
    },
    {
        id = "seraphic_reliquary",
        name = "Seraphic Reliquary",
        rarity = "BIBLICAL",
        value = 18_000,
        incomePerHour = 1_250,
        category = "Relic",
    },
    {
        id = "genesis_echo_chalice",
        name = "Genesis Echo Chalice",
        rarity = "BIBLICAL",
        value = 22_000,
        incomePerHour = 1_500,
        category = "Chalice",
    },
}

for _, collectible in Collectibles do
    table.freeze(collectible)
end

table.freeze(Collectibles)

return Collectibles
